### ISSUE TITLE
File input component doesn't show the name of the uploaded files

### ISSUE THREAD

**Issue by ManishAradwad** [writer/writer-framework#299]
The component shows "No Files Uploaded" after uploading the files. The uploaded files are available in the code, though. I feel the component should signify that files have been uploaded.

**Comment by FabienArcellier** [comment]
Thank you for your feedback, we will rework this component in the coming weeks. PR #142 is open for a long time on this topic.

**Comment by ramedina86** [comment]
The _File Input_ has been improved and now shows the file name.

**Comment by madeindjs** [comment]
For reference, it was https://github.com/writer/writer-framework/pull/494
