### ISSUE TITLE
Multi choice dropdopw choices in a section does not show all options and is cutoff

### ISSUE THREAD

**Issue by thondeboer** [writer/writer-framework#380]
I created a multichoice dropdown inside a section, but the values are not all showing since it is cropped to fit inside the section.

![image](https://github.com/streamsync-cloud/streamsync/assets/3422829/1aced051-5ea8-4e1b-9c5d-cbb3884ddbe4)

**Comment by thondeboer** [comment]
Using streamsync 0.4 and firefox as the browser but same issue in chrome.

**Comment by thondeboer** [comment]
Additionally, I would like it better if the options for the multichoice used the KEYS to show as the labels and the values should be the data to return. This way you can sort the keys since it seems even if I give it a sorted dict, where the VALUES are sorted (since that is what you show) it still seems to revert to sorting on the keys itself.

**Comment by hallvardnmbu** [comment]
I did a work-around by mocking the "Section" by using a HTML object, and dragging the select-component into it.

<img width="238" alt="Closed" src="https://github.com/user-attachments/assets/77e8fce0-348b-4811-8cd3-0b36160fbff6">

<img width="245" alt="Open" src="https://github.com/user-attachments/assets/1e113c5a-0fd2-4e82-8aab-b085a1875eb3">

<img width="664" alt="HTML Element" src="https://github.com/user-attachments/assets/388da9a3-9668-4d18-bef3-719a43633ae7">

**Comment by madeindjs** [comment]
Helllo guys, I'm working on a potential fix to solve the issue. It just seems a `overflow: hidden` issue.

> I would like it better if the options for the multichoice used the KEYS to show as the labels and the values should be the data to return. This way you can sort the keys since it seems even if I give it a sorted dict, where the VALUES are sorted (since that is what you show) it still seems to revert to sorting on the keys itself.

@thondeboer , Yes, the order of keys are not preserved.  I'm affraid we can't use the JSON value as HTML value since it's a breaking change...
