### ISSUE TITLE
Feature request: Add search and keyboard shortcuts to toolkit

### ISSUE THREAD

**Issue by samjulien** [writer/writer-framework#407]
Would be great from a DX perspective to add the same search functionality that's in the component tree to the toolkit. It's going to get tedious looking up each component in the list. Bonus points if we can add keyboard shortcuts to search in either tree (e.g. "/" or "cmd-K").
![Screenshot 2024-04-26 at 1 05 53 PM (1)](https://github.com/streamsync-cloud/streamsync/assets/7738189/711ee811-025b-4a7e-8ca1-a110a93a5b05)

**Comment by ramedina86** [comment]
@samjulien This has been developed and merged, we'll be shipping it soon.

**Comment by madeindjs** [comment]
For reference, it was https://github.com/writer/writer-framework/pull/516
