### ISSUE TITLE
Question: How to clear the chat bot window?

### ISSUE THREAD

**Issue by thondeboer** [writer/writer-framework#411]
Great little addition, the chatbot. Just when I needed one.
Quick question; How do you clear the chat window for a new chat?

**Comment by ramedina86** [comment]
Hey, we faced some issues with the current design. We'll be reengineering it so that the conversation is in state. This will enable:

- Streaming
- Loading old conversations
- Clearing conversations

As of now, it's not possible. We'll release the new version at the end of month.

**Comment by chew1976** [comment]
> Hey, we faced some issues with the current design. We'll be reengineering it so that the conversation is in state. This will enable:
> 
> * Streaming
> * Loading old conversations
> * Clearing conversations
> 
> As of now, it's not possible. We'll release the new version at the end of month.

This is great news! I look forward to being able to regenerate responses as well as modify them when using LLM.

**Comment by FabienArcellier** [comment]
Since version 0.6, you can clear chat content. I think this improvement has been developped by @mmikita95.

```
def clear_conversation(state):
    # initializes a new conversation instead of existing one
    state["chatbot_conversation"] = Conversation() 
```
