### ISSUE TITLE
Dropdown bug. can't select Bug

### ISSUE THREAD

**Issue by pandadezzz** [writer/writer-framework#459]
I think there is a bug with dropdown. i can see the items in dropdown but it doesn't click. sometimes it works but rarely?
I tried it with old Streamsync version and had no issues there.

**Comment by ramedina86** [comment]
Hi, thanks for reporting, I can confirm it's a bug. We'll release a fixed version later today.

**Comment by ramedina86** [comment]
Fixed in v0.6.1, thanks again for reporting.

**Comment by pandadezzz** [comment]
thanks!
