### ISSUE TITLE
HTML in displayed strings

### ISSUE THREAD

**Issue by hallvardnmbu** [writer/writer-framework#502]
Hi,

I've been using the framework for a while, and I'm really enjoying it! Great job.

One thing I'm missing is the possibility of using "raw" HTML within visible values. 

For instance, I have a `Multiselect Input`-component, where I want to display both valid and invalid choices. I would then like to have the valid options another colour than the invalid ones. 

```python
dropdown = {value1: f"<p style='color: blue;'>{value1}</p>", ...}
```

Is there a way to do this already, or is it possible to add?

Thanks!

**Comment by FabienArcellier** [comment]
Thanks for this suggestion. The need is clearly expressed. You must be able to differentiate between choices by their format. We will study it to identify whether offering this degree of freedom is viable. We already have components that render html.

Today, I suppose if you want to do this, you need to create your own custom component.

**Comment by hallvardnmbu** [comment]
OK. Thanks for the feedback!
