### ISSUE TITLE
Collapsable navigation bar

### ISSUE THREAD

**Issue by hallvardnmbu** [writer/writer-framework#506]
I'm a huge fan of the collapsable leftbar. Is it possible to add a similar one — which is horizontal (top and/or bottom)? Maybe the positioning on the page could be an option, like the contents of columns are.

Or, alternatively an element (section-like) which can be collapsed/expanded.

**Comment by FabienArcellier** [comment]
Can you share a design idea for this bar at the top? Where should it open?

The ability to expand section dynamically is interesting. We will take a look.

**Comment by hallvardnmbu** [comment]
[Here](https://www.vinmonopolet.no) they have two implementations of navigation bars. One static top bar (shaded dark blue) and one that automatically collapses when scrolling. 

Maybe this could be one component, with a "setting" describing its dynamics? E.g., `static`, `toggleable`, `dynamic`.

Also, the positioning on the page would be a nice "setting" (i.e., `left`, `right`, `top` and `bottom`).

Thus, the `Sidebar` could be used as the "base" (maybe renamed to `Navbar` or something alike?), and the mentioned settings as possibilities in the editor.

**Comment by hallvardnmbu** [comment]
And [here](https://www.vinmonopolet.no/drikkevelger) is an example of an expandable section.
