### ISSUE TITLE
Connection rejected.

### ISSUE THREAD

**Issue by bnxvs** [writer/writer-framework#528]
Any attempt to start results in an error: “Connection rejected.” (MacOS Sonoma M1, Python 3.11)

**Comment by FabienArcellier** [comment]
Hi,

Are you running through docker or directly in python ? Could you share a template of the project that reproduce the problem ?

Regards,

**Comment by bnxvs** [comment]
Directly in python. I was just trying to run the "hello" example.
> writer hello
> writer run hello
> writer edit hello
> writer edit hello --enable-remote-edit --port=8080
Any launch option results in an "Connection rejected." error.

**Comment by FabienArcellier** [comment]
Does this error happen in your browser or in the terminal ? 
Are you using the current version of writer (0.7.0) ? `writer --version`

```
pip install writer
```

Could you share the list of network port that are listening on your machine ?

```
sudo lsof -PiTCP -sTCP:LISTEN
```

**Comment by FabienArcellier** [comment]
We don't know what would be the root cause. 

Could you make a try with a simple python webserver ? You can create a file `index.html` and see if you can load it

```bash
python3 -m http.server 3006
```

**Comment by FabienArcellier** [comment]
Have you been able to make progress on this subject and identify a blocking area?
