### ISSUE TITLE
Custom styles for image container

### ISSUE THREAD

**Issue by yanomaly** [writer/writer-framework#531]
I wanted to show authenticated user data (name and avatar), but avatar picture is uploading in square format. 
I tried to make it square (just applied custom css with “border-radius: 50%” property).  

| Apply custom style to Image container | Custom css class |
|     :---:      |     :---:      |
| ![Screenshot from 2024-08-23 12-04-41](https://github.com/user-attachments/assets/aceadc55-ce78-475e-88bb-99a451cacc30) | ![Screenshot from 2024-08-23 12-04-51](https://github.com/user-attachments/assets/8f9e2d80-edbc-4c01-ad09-71a6fc9b5a83) |

But that custom css style property is applied to container class, not for image. You can see, that picture overlays a container and container is round but picture is not. 

![Screenshot from 2024-08-23 12-05-01](https://github.com/user-attachments/assets/53e56bf6-05ba-4060-8c71-afdf98704451)

That issue is easy to fix: just apply style directly to image inside container. But if it is expected behavior? 

![Screenshot from 2024-08-23 12-06-43](https://github.com/user-attachments/assets/01aa4d4f-64cf-4619-97ab-464a1009722f)

**Comment by ramedina86** [comment]
This is expected behavior and is documented at https://dev.writer.com/framework/stylesheets

> You can use the property Custom CSS classes in the Builder’s Component Settings to apply classes to a component, separated by spaces. Internally, this will apply the classes to the root HTML element of the rendered component.

If we targeted only the `img`, and you wanted to apply CSS to the Image Caption, you wouldn't be able to do it.
