### ISSUE TITLE
Apply suctom styles to images dynamically

### ISSUE THREAD

**Issue by yanomaly** [writer/writer-framework#532]
It's a continuation of Issue #531 but about reapplyment of custom styles. After solution of #531 issue I 100% sure that current css file is correct and linked with image. But, after login into account, picture is still square, not rounded. So I tried to open an explorer and see if there is custom style is applied to image, but I didn't find it. Also after default page loading in editor mode without login everything is fine and style has applied. 
| Interface Instance | Explorer info about css |
|     :---:      |     :---:      |
| ![image](https://github.com/user-attachments/assets/78d8363b-1046-4d35-908e-fce9520cc73e) | ![image](https://github.com/user-attachments/assets/909c26b3-308b-4f60-bf9b-9cb318e58498) |
| ![image](https://github.com/user-attachments/assets/3ccd079f-b90b-43fa-af5f-a6314b1e7ccf) | ![image](https://github.com/user-attachments/assets/6429cc56-1bc1-4d65-9346-55763a8b8d27) |

**Comment by ramedina86** [comment]
Most likely you're experiencing caching of the CSS, so you'll need to force refresh. This is also documented.

> Use versions to avoid caching. During development time, stylesheets may be cached by your browser, preventing updates from being reflected. Append a querystring to bust the cache, e.g. use /static/custom.css?3.
