### ISSUE TITLE
plotly.express.scatter_mapbox deprecated from v5.24

### ISSUE THREAD

**Issue by khliland** [writer/writer-framework#635]
From Plotly version 5.24, Mapboxes have been deprecated and superseded by scatter_map and similar. However, scatter_map renders only as a grey tiled rectangle and does not contain any maps when combined with Writer.

**Comment by ramedina86** [comment]
Thanks @khliland for reporting this - we're looking into it.

**Comment by FabienArcellier** [comment]
I reproduced the problem on this application. I fixed it by updating `plotly.js-dist-min` and `plotly`. I will open a PR.

[mymap.zip](https://github.com/user-attachments/files/17827128/mymap.zip)
